import type { FieldConfig } from "../../../../interfaces/components.interface";
import type { CreateExpedientPatientDto } from "../../../../interfaces/user.interface";


export const configForm = (): FieldConfig<CreateExpedientPatientDto>[] => [
  {
    key: "title1",
    type: "title",
    valueInitial: "Identificación",
    level:4,
    xs: 24,
    md: 24,
  },
  {
    key: "medicalRecord",
    type: "readOnly",
    label: "No. de Expediente",
    valueInitial: "Exp8421",
    textTransform:"uppercase",
    xs: 24,
    md: 8,
  },
  {
    key: "recordDate",
    type: "readOnly",
    label: "Documento de Identidad",
    valueInitial: "03892041-5",
    xs: 24,
    md: 8,
  },
   {
    key: "recordDate",
    type: "readOnly",
    label: "Fecha de Registro",
    valueInitial: "12/05/2025",
    xs: 24,
    md: 8,
  },
  {
    key:"divider1",
    type:"divider",
    xs:24
  },
  {
    key: "title2",
    type: "title",
    valueInitial: "General",
    level:4,
    xs: 24,
    md: 24,
  },
  {
    key: "firstName",
    type: "readOnly",
    label: "Nombre",
    valueInitial: "Richard",
    xs: 24,
    md: 8,
  },
  {
    key: "lastName",
    type: "readOnly",
    label: "Apellido",
    valueInitial: "Payne",
    xs: 24,
    md: 8,
  },
  {
    key: "age",
    type: "readOnly",
    label: "Edad",
    valueInitial: "47",
    xs: 24,
    md: 8,
  },
  {
    key: "dateOfBirth",
    type: "readOnly",
    label: "Fecha de Nacimiento",
    valueInitial: "14/06/1978",
    xs: 24,
    md: 8,
  },
  {
    key: "gender",
    type: "readOnly",
    label: "Género",
    valueInitial: "Masculino",
    xs: 24,
    md: 8,
  },
  {
    key: "nationality",
    type: "readOnly",
    label: "Nacionalidad",
    valueInitial: "Salvadoreña",
    xs: 24,
    md: 8,
  },
  {
    key:"divider1",
    type:"divider",
    xs:24
  },
  {
    key: "title3",
    type: "title",
    valueInitial: "Contacto",
    level:4,
    xs: 24,
    md: 24,
  },
  {
    key: "phoneNumber1",
    type: "readOnly",
    label: "Teléfono",
    valueInitial: "+503 22457896",
    xs: 24,
    md: 8,
  },
  {
    key: "phoneNumber2",
    type: "readOnly",
    label: "Teléfono Movil",
    valueInitial: "+503 78965412",
    xs: 24,
    md: 16,
  },
  {
    key:"divider1",
    type:"divider",
    xs:24
  },
  {
    key: "title4",
    type: "title",
    valueInitial: "Dirección",
    level:4,
    xs: 24,
    md: 24,
  },
  {
    key: "address",
    type: "readOnly",
    label: "Dirección Residencial",
    valueInitial: "residencial altavista pje #1",
    textTransform:"uppercase",
    xs: 24,
    md: 8,
  },
  {
    key: "country",
    type: "readOnly",
    label: "Ciudad",
    valueInitial: "Soyapango",
    xs: 24,
    md: 8,
  },
  {
    key: "department",
    type: "readOnly",
    label: "Departamento",
    valueInitial: "San Salvador Sur",
    xs: 24,
    md: 8,
  },
  {
    key: "housingLocation",
    type: "readOnly",
    label: "Ubicación de la Residencia",
    valueInitial: "San Salvador Sur",
    xs: 24,
    md: 8,
  },
   {
    key:"divider1",
    type:"divider",
    xs:24
  },
  {
    key: "title5",
    type: "title",
    valueInitial: "Educación y más",
    level:4,
    xs: 24,
    md: 24,
  },
   {
    key: "education",
    type: "readOnly",
    label: "Educación",
    valueInitial: "Bachiller",
    xs: 24,
    md: 8,
  },
  {
    key: "wearsGlasses",
    type: "readOnly",
    label: "Usa Lentes",
    valueInitial: "Si",
    xs: 24,
    md: 8,
  },
  {
    key: "readAndWrite",
    type: "readOnly",
    label: "Lee y Escribe",
    valueInitial: "Si",
    xs: 24,
    md: 8,
  },
  {
    key:"divider1",
    type:"divider",
    xs:24
  },
  {
    key: "title6",
    type: "title",
    valueInitial: "Situación Laboral",
    level:4,
    xs: 24,
    md: 24,
  },
  {
    key: "occupation",
    type: "readOnly",
    label: "Ocupación",
    valueInitial: "Empleado Administrativo",
    xs: 24,
    md: 8,
  },
  {
    key: "category",
    type: "readOnly",
    label: "Categoria",
    valueInitial: "-",
    xs: 24,
    md: 8,
  },
];

export const breadcrumb = [
  { label: "Inicio", path: "/" },
  { label: "Crear Paciente" },
];
