import type { FieldConfig } from "../../../../interfaces/components.interface";
import type { CreateExpedientPatientDto } from "../../../../interfaces/user.interface";


export const configFormExpedient = (): FieldConfig<CreateExpedientPatientDto>[] => [
  {
    key: "fullName",
    type: "title",
    valueInitial: "Richard Payne",
    fontWeight:"bold",
    margin:"0 0 15px 0",
    level:2,
    xs: 24,
    md: 24,
  },
  {
    key: "medicalRecord",
    type: "readOnly",
    label: "Número de Expediente",
    valueInitial: "10938475",
     typeText:"secondary",
    fontWeight:"normal",
    fontSize:"16px",
    xs: 24,
    md: 12,
  },
  {
    key: "recordDate",
    type: "readOnly",
    label: "Número de DUI",
    valueInitial: "03892041-5",
     typeText:"secondary",
    fontWeight:"normal",
    fontSize:"16px",
    xs: 24,
    md: 12,
  },
   {
    key: "gender",
    type: "readOnly",
    label: "Género",
    valueInitial: "Masculino",
        typeText:"secondary",
    fontWeight:"normal",
    fontSize:"16px",
    xs: 24,
    md: 7,
  },
  {
    key: "age",
    type: "readOnly",
    label: "Edad",
    valueInitial: "47 años",
        typeText:"secondary",
    fontWeight:"normal",
    fontSize:"16px",
    xs: 24,
    md: 6,
  },
  {
    key: "dateOfBirth",
    type: "readOnly",
    label: "Fecha de Nacimiento",
    valueInitial: "12/04/1987",
    typeText:"secondary",
    fontWeight:"normal",
    fontSize:"16px",
    xs: 24,
    md: 11,
  },
  {
    key:"divider1",
    type:"divider",
    xs:24
  },
  
];  

export const configFormExpedientFooter = (): FieldConfig<CreateExpedientPatientDto>[] => [
  {
    key: "titleFooter",
    type: "title",
    valueInitial: "Último Diagnóstico",
    fontWeight:"400",
    color:"#00000070",
    level:5,
    xs: 24,
    md: 24,
  },
  {
    key: "date",
    type: "readOnly",
    label: "Fecha",
    valueInitial: "12/04/2024",
     typeText:"secondary",
    fontWeight:"normal",
    fontSize:"16px",
    xs: 24,
    md: 7,
  },
  {
    key: "diagnosis",
    type: "readOnly",
    label: "Diagnóstico",
    valueInitial: "Cataratas",
     typeText:"secondary",
    fontWeight:"normal",
    fontSize:"16px",
    xs: 24,
    md: 7,
  },
   {
    key: "doctor",
    type: "readOnly",
    label: "Doctor",
    valueInitial: "Robert Downy",
        typeText:"secondary",
    fontWeight:"normal",
    fontSize:"16px",
    xs: 24,
    md: 10,
  },  
];  
